<?php
if(!defined('IN_JQNEWS')) exit('Access Denied');
$_SGLOBAL['model_3_field']=Array
	(
	'contentid' => Array
		(
		'fieldid' => 89,
		'modelid' => 3,
		'field' => 'contentid',
		'name' => 'ID',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => 1,
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => '0',
		'disabled' => '0'
		),
	'catid' => Array
		(
		'fieldid' => 90,
		'modelid' => 3,
		'field' => 'catid',
		'name' => '栏目',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 6,
		'pattern' => '/^[0-9]{1,6}$/',
		'errortips' => '请选择栏目',
		'formtype' => 'catid',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 1,
		'disabled' => '0'
		),
	'typeid' => Array
		(
		'fieldid' => 91,
		'modelid' => 3,
		'field' => 'typeid',
		'name' => '类别',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'typeid',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 2,
		'disabled' => 1
		),
	'areaid' => Array
		(
		'fieldid' => 92,
		'modelid' => 3,
		'field' => 'areaid',
		'name' => '地区',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'areaid',
		'setting' => 'Array
	(
	\'items\' => \'\',
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 3,
		'disabled' => 1
		),
	'title' => Array
		(
		'fieldid' => 93,
		'modelid' => 3,
		'field' => 'title',
		'name' => '标题',
		'tips' => '',
		'css' => 'inputtitle',
		'minlength' => 1,
		'maxlength' => 80,
		'pattern' => '',
		'errortips' => '标题字符长度必须为1到80位！',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 80,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => ' onBlur="$.post(\'/modules/news/admin/?ac=content&ajax_request=1\', { op : \'dict_word\',data:$(\'#title\').val()}, function(data){if(data && $(\'#keywords\').val()==\'\') $(\'#keywords\').val(data); })" ',
		'forminfo' => '  <input type="button" value="检测标题是否已存在" onclick="$.post(\'/modules/news/admin/?ac=content&ajax_request=1&op=check_field&mod=down\', {title:$(\'#title\').val(),version:$(\'#version\').val(),catid:$(\'#catid\').val()}, function(data){ $(\'#t_msg\').html(data); })">&nbsp;<span style="color:\'#ff0000\'" id=\'t_msg\'></span>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 4,
		'disabled' => '0'
		),
	'version' => Array
		(
		'fieldid' => 104,
		'modelid' => 3,
		'field' => 'version',
		'name' => '版本号',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 20,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 4,
		'disabled' => '0'
		),
	'style' => Array
		(
		'fieldid' => 94,
		'modelid' => 3,
		'field' => 'style',
		'name' => '颜色和字型',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 30,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'hidden',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => ' <select name="style_color1" id="style_color1" onchange="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value +=  \' \'+document.all.style_strong1.value;"><option value="">颜色</option><option value="c1"  class="bg1"></option><option value="c2"  class="bg2"></option><option value="c3"  class="bg3"></option><option value="c4"  class="bg4"></option><option value="c5"  class="bg5"></option><option value="c6"  class="bg6"></option><option value="c7"  class="bg7"></option><option value="c8"  class="bg8"></option><option value="c9"  class="bg9"></option><option value="c10"  class="bg10"></option><option value="c11"  class="bg11"></option><option value="c12"  class="bg12"></option><option value="c13"  class="bg13"></option><option value="c14"  class="bg14"></option><option value="c15"  class="bg15"></option></select><label><input type="checkbox" name="style_strong1" id="style_strong1" value="b" onclick="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value += \' \'+document.all.style_strong1.value;"> 加粗</label><script>if(document.all.style.value!=\'\'){var temp=document.all.style.value;if(temp.indexOf("b")!=-1){document.all.style_strong1.checked=true;}var sint=temp.replace(/[^\\d]*/ig,"");if(sint!=\'\'){document.all.style_color1.selectedIndex = sint;}}</script>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 5,
		'disabled' => '0'
		),
	'thumb' => Array
		(
		'fieldid' => 95,
		'modelid' => 3,
		'field' => 'thumb',
		'name' => '缩略图',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'image',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\',
	\'maxsize\' => \'\',
	\'fileextname\' => \'jpg,jpeg,gif,png,bmp\',
	\'isselectimage\' => 1,
	\'enablesaveimage\' => 1,
	\'thumb_enable\' => -1,
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => -1,
	\'attachwimage\' => \'watermark.gif\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 6,
		'disabled' => '0'
		),
	'keywords' => Array
		(
		'fieldid' => 96,
		'modelid' => 3,
		'field' => 'keywords',
		'name' => '关键词',
		'tips' => '多个关键词之间用空格隔开',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 40,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '<select name="" onchange="$(\'#keywords\').val($(\'#keywords\').val()+this.value+\' \')" style="width:85px"><option>常用关键词</option><option value=黎明>黎明</option><option value=王爱红>王爱红</option></select>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 7,
		'disabled' => '0'
		),
	'description' => Array
		(
		'fieldid' => 97,
		'modelid' => 3,
		'field' => 'description',
		'name' => '摘要',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'textarea',
		'setting' => 'array (
  \'rows\' => \'4\',
  \'cols\' => \'50\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'\',
  \'checkcharacter\' => \'1\',
)',
		'formattribute' => 'style="width:80%" onkeyup="checkLength(this, \'description\', \'255\');"',
		'forminfo' => ' <br /><img src="/modules/news/images/icon.gif" width="12"> 还可以输入 <font id="ls_description" color="#ff0000;">255</font> 个字符！',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 8,
		'disabled' => '0'
		),
	'userid' => Array
		(
		'fieldid' => 98,
		'modelid' => 3,
		'field' => 'userid',
		'name' => '发布人',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'userid',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 9,
		'disabled' => '0'
		),
	'updatetime' => Array
		(
		'fieldid' => 99,
		'modelid' => 3,
		'field' => 'updatetime',
		'name' => '更新时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 10,
		'disabled' => '0'
		),
	'content' => Array
		(
		'fieldid' => 100,
		'modelid' => 3,
		'field' => 'content',
		'name' => '描述',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 999999,
		'pattern' => '',
		'errortips' => '请填写文章内容！',
		'formtype' => 'editor',
		'setting' => 'Array
	(
	\'toolbar\' => \'basic\',
	\'width\' => \'100%\',
	\'height\' => 300,
	\'defaultvalue\' => \'\',
	\'storage\' => \'database\',
	\'thumb_enable\' => -1,
	\'thumb_width\' => 600,
	\'thumb_height\' => 600,
	\'attachwater\' => -1,
	\'attachwimage\' => \'\',
	\'enablesaveimage\' => 1,
	\'enablesaveflash\' => \'0\',
	\'savefileext\' => \'mp3|rar|zip\',
	\'forbidwords\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 11,
		'disabled' => '0'
		),
	'downurl' => Array
		(
		'fieldid' => 101,
		'modelid' => 3,
		'field' => 'downurl',
		'name' => '下载地址',
		'tips' => '',
		'css' => '',
		'minlength' => 4,
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'select',
		'setting' => 'Array
	(
	\'items\' => \'http://tel.xxx.com/|电信下载
http://cnc.xxx.com/|网通下载
http://dnc.xxx.com/|长城下载\',
	\'size\' => 1,
	\'defaultvalue\' => \'http://dnc.xxx.com/\',
	\'multiple\' => \'0\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 20,
		'disabled' => '0'
		),
	'downurls' => Array
		(
		'fieldid' => 102,
		'modelid' => 3,
		'field' => 'downurls',
		'name' => '专用下载下载列表',
		'tips' => '名称|下载地址',
		'css' => '',
		'minlength' => 6,
		'maxlength' => 99999,
		'pattern' => '',
		'errortips' => '请将下载地址填写完整！',
		'formtype' => 'files',
		'setting' => 'Array
	(
	\'rows\' => 6,
	\'cols\' => 70,
	\'defaultvalue\' => \'\',
	\'enablehtml\' => 1,
	\'maxsize\' => 1024,
	\'fileextname\' => \'\',
	\'thumb_enable\' => \'0\',
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => \'0\',
	\'attachwimage\' => \'\'
	)',
		'formattribute' => 'style="width:100%"',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 20,
		'disabled' => '0'
		),
	'pics' => Array
		(
		'fieldid' => 372,
		'modelid' => 3,
		'field' => 'pics',
		'name' => '组图',
		'tips' => '批量上传图片',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 999999,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'images',
		'setting' => 'Array
	(

	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 20,
		'disabled' => '0'
		),
	'downloadc' => Array
		(
		'fieldid' => 421,
		'modelid' => 3,
		'field' => 'downloadc',
		'name' => '常规下载',
		'tips' => '常规下载列表',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'files',
		'setting' => 'Array
	(
	\'rows\' => 6,
	\'cols\' => 70,
	\'defaultvalue\' => \'\',
	\'enablehtml\' => \'0\',
	\'maxsize\' => 1024,
	\'fileextname\' => \'\',
	\'thumb_enable\' => \'0\',
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => \'0\',
	\'attachwimage\' => \'\'
	)',
		'formattribute' => 'style="width:100%"',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 20,
		'disabled' => '0'
		),
	'filesize' => Array
		(
		'fieldid' => 103,
		'modelid' => 3,
		'field' => 'filesize',
		'name' => '文件大小',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 10,
	\'defaultvalue\' => \'未知\'
	)',
		'formattribute' => 'onfocus="if(this.value==\'未知\') this.value=\'\';" onblur="if(this.value==\'\') this.value=\'未知\';"',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 21,
		'disabled' => '0'
		),
	'classtype' => Array
		(
		'fieldid' => 105,
		'modelid' => 3,
		'field' => 'classtype',
		'name' => '软件类型',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'select',
		'setting' => 'Array
	(
	\'items\' => \'国产软件|国产软件
国外软件|国外软件
汉化补丁|汉化补丁
程序源码|程序源码
其他|其他\',
	\'size\' => 1,
	\'defaultvalue\' => \'国产软件\',
	\'multiple\' => \'0\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 23,
		'disabled' => '0'
		),
	'language' => Array
		(
		'fieldid' => 106,
		'modelid' => 3,
		'field' => 'language',
		'name' => '软件语言',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'select',
		'setting' => 'Array
	(
	\'items\' => \'英文|英文
简体中文|简体中文
繁体中文|繁体中文
简繁中文|简繁中文
多国语言|多国语言
其他语言|其他语言\',
	\'size\' => 1,
	\'defaultvalue\' => \'简体中文\',
	\'multiple\' => \'0\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 24,
		'disabled' => '0'
		),
	'copytype' => Array
		(
		'fieldid' => 107,
		'modelid' => 3,
		'field' => 'copytype',
		'name' => '软件授权形式',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 15,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'select',
		'setting' => 'Array
	(
	\'items\' => \'免费版|免费版
共享版|共享版
试用版|试用版
演示版|演示版
注册版|注册版
破解版|破解版
零售版|零售版
OEM版|OEM版\',
	\'size\' => 1,
	\'defaultvalue\' => \'免费版\',
	\'multiple\' => \'0\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 25,
		'disabled' => '0'
		),
	'systems' => Array
		(
		'fieldid' => 108,
		'modelid' => 3,
		'field' => 'systems',
		'name' => '软件平台',
		'tips' => '<select name=\'selectSystem\' onchange="ChangeInput(this,document.myform.systems,\'/\')">
	<option value=\'WinXP\'>WinXP</option>
	<option value=\'Vista\'>Vista</option>
	<option value=\'Win2000\'>Win2000</option>
	<option value=\'Win2003\'>Win2003</option>
	<option value=\'Unix\'>Unix</option>
	<option value=\'Linux\'>Linux</option>
	<option value=\'MacOS\'>MacOS</option>
</select>',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'Win2000/WinXP/Win2003\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 26,
		'disabled' => '0'
		),
	'stars' => Array
		(
		'fieldid' => 109,
		'modelid' => 3,
		'field' => 'stars',
		'name' => '评分等级',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'radio',
		'setting' => 'Array
	(
	\'items\' => \'★☆☆☆☆|★☆☆☆☆
★★☆☆☆|★★☆☆☆
★★★☆☆|★★★☆☆
★★★★☆|★★★★☆
★★★★★|★★★★★\',
	\'defaultvalue\' => \'★★★☆☆\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 27,
		'disabled' => '0'
		),
	'inputtime' => Array
		(
		'fieldid' => 110,
		'modelid' => 3,
		'field' => 'inputtime',
		'name' => '发布时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'Array
	(
	\'format\' => \'Y-m-d H:i\',
	\'defaulttype\' => 1,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 30,
		'disabled' => '0'
		),
	'url' => Array
		(
		'fieldid' => 111,
		'modelid' => 3,
		'field' => 'url',
		'name' => '转向链接',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => 'readonly',
		'forminfo' => '  <font color="#FF0000"><label><input type="checkbox" id="linkurl" value="1" onclick="javascript:if(this.checked==true) $(\'#url\').attr(\'readonly\',\'\');else $(\'#url\').attr(\'readonly\',\'true\');" > 转向链接</label></font><br/><font color="#FF0000">如果使用转向链接则点击标题就直接跳转而内容设置无效</font>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 31,
		'disabled' => '0'
		),
	'posids' => Array
		(
		'fieldid' => 112,
		'modelid' => 3,
		'field' => 'posids',
		'name' => '推荐位',
		'tips' => '全选<input boxid=\'posids\' type=\'checkbox\' onclick="checkall(\'posids\')" >',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'posid',
		'setting' => 'Array
	(

	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 32,
		'disabled' => '0'
		),
	'groupids_view' => Array
		(
		'fieldid' => 113,
		'modelid' => 3,
		'field' => 'groupids_view',
		'name' => '下载权限',
		'tips' => '全选<input boxid=\'groupids_view\' type=\'checkbox\' onclick="checkall(\'groupids_view\')" >',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'groupid',
		'setting' => 'array (
  \'priv\' => \'view\',
  \'cols\' => \'4\',
  \'width\' => \'125\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => -99,
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 33,
		'disabled' => '0'
		),
	'readpoint' => Array
		(
		'fieldid' => 114,
		'modelid' => 3,
		'field' => 'readpoint',
		'name' => '阅读所需点数',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 5,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => 'Array
	(
	\'minnumber\' => \'0\',
	\'maxnumber\' => 99999,
	\'decimaldigits\' => 1,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 34,
		'disabled' => '0'
		),
	'prefix' => Array
		(
		'fieldid' => 115,
		'modelid' => 3,
		'field' => 'prefix',
		'name' => 'html文件名',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'array (
  \'size\' => \'20\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => -99,
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 35,
		'disabled' => '0'
		),
	'listorder' => Array
		(
		'fieldid' => 117,
		'modelid' => 3,
		'field' => 'listorder',
		'name' => '排序',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 6,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 97,
		'disabled' => '0'
		),
	'status' => Array
		(
		'fieldid' => 118,
		'modelid' => 3,
		'field' => 'status',
		'name' => '状态',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 2,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 98,
		'disabled' => '0'
		)
	)
?>