<?php
if(!defined('IN_JQNEWS')) exit('Access Denied');
$_SGLOBAL['model']=Array
	(
	'1' => Array
		(
		'modelid' => 1,
		'name' => '新闻',
		'description' => '文章内容发布！',
		'tablename' => 'news',
		'itemname' => '新闻',
		'itemunit' => '篇',
		'workflowid' => 1,
		'template_category' => 'category_news.html',
		'template_list' => 'list_news.html',
		'template_show' => 'show_news.html',
		'template_print' => 'print',
		'ishtml' => 3,
		'show_ishtml' => 1,
		'category_urlrule' => '',
		'list_urlrule' => 'list-{$catid}-{$page}.html',
		'show_urlrule' => '{$contentid}_{$page}',
		'enablesearch' => 1,
		'ischeck' => 1,
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => 'content'
		),
	'2' => Array
		(
		'modelid' => 2,
		'name' => '图片',
		'description' => '图片内容发布！',
		'tablename' => 'picture',
		'itemname' => '图片',
		'itemunit' => '张',
		'workflowid' => 1,
		'template_category' => 'category_picture',
		'template_list' => 'list_picture',
		'template_show' => 'show_picture',
		'template_print' => 'print',
		'ishtml' => 2,
		'show_ishtml' => 2,
		'category_urlrule' => '',
		'list_urlrule' => '0',
		'show_urlrule' => '',
		'enablesearch' => 1,
		'ischeck' => '0',
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => 'pictureurls'
		),
	'3' => Array
		(
		'modelid' => 3,
		'name' => '下载',
		'description' => '游戏下载频道！',
		'tablename' => 'down',
		'itemname' => '下载',
		'itemunit' => '条',
		'workflowid' => 1,
		'template_category' => 'category_down',
		'template_list' => 'list_down|list_down_2',
		'template_show' => 'show_down',
		'template_print' => 'print',
		'ishtml' => 2,
		'show_ishtml' => 2,
		'category_urlrule' => 'list-{$catid}-{$page}',
		'list_urlrule' => '0',
		'show_urlrule' => '{$contentid}/{$page}',
		'enablesearch' => 1,
		'ischeck' => 1,
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => ''
		),
	'28' => Array
		(
		'modelid' => 28,
		'name' => '专题',
		'description' => '专题数据聚合！',
		'tablename' => 'special',
		'itemname' => '专题',
		'itemunit' => '篇',
		'workflowid' => 1,
		'template_category' => 'category_special',
		'template_list' => 'list_special',
		'template_show' => 'show_special',
		'template_print' => '',
		'ishtml' => 2,
		'show_ishtml' => 2,
		'category_urlrule' => '',
		'list_urlrule' => '0',
		'show_urlrule' => '',
		'enablesearch' => 1,
		'ischeck' => 1,
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => ''
		),
	'29' => Array
		(
		'modelid' => 29,
		'name' => '视频',
		'description' => '视频发布平台！',
		'tablename' => 'video',
		'itemname' => '视频',
		'itemunit' => '条',
		'workflowid' => 1,
		'template_category' => 'category_video',
		'template_list' => 'list_video',
		'template_show' => 'show_video',
		'template_print' => '',
		'ishtml' => 2,
		'show_ishtml' => 2,
		'category_urlrule' => '',
		'list_urlrule' => '0',
		'show_urlrule' => '',
		'enablesearch' => 1,
		'ischeck' => 1,
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => 'video'
		),
	'31' => Array
		(
		'modelid' => 31,
		'name' => '帮助',
		'description' => '',
		'tablename' => 'xx',
		'itemname' => '帮助中心',
		'itemunit' => '帮助中心',
		'workflowid' => 1,
		'template_category' => '帮助中心',
		'template_list' => '帮助中心',
		'template_show' => '帮助中心',
		'template_print' => '',
		'ishtml' => 2,
		'show_ishtml' => 2,
		'category_urlrule' => '',
		'list_urlrule' => '0',
		'show_urlrule' => '',
		'enablesearch' => 1,
		'ischeck' => 1,
		'isrelated' => 1,
		'disabled' => '0',
		'pagefield' => 'content'
		)
	)
?>