<?php
if(!defined('IN_JQNEWS')) exit('Access Denied');
$_SGLOBAL['model_28_field']=Array
	(
	'contentid' => Array
		(
		'fieldid' => 374,
		'modelid' => 28,
		'field' => 'contentid',
		'name' => 'ID',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => 1,
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => '0',
		'disabled' => '0'
		),
	'catid' => Array
		(
		'fieldid' => 375,
		'modelid' => 28,
		'field' => 'catid',
		'name' => '所属类别',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 9999,
		'pattern' => '/^[0-9]+$/',
		'errortips' => '请选择所属栏目',
		'formtype' => 'catid',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 1,
		'disabled' => '0'
		),
	'typeid' => Array
		(
		'fieldid' => 376,
		'modelid' => 28,
		'field' => 'typeid',
		'name' => '类别',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'typeid',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 2,
		'disabled' => 1
		),
	'areaid' => Array
		(
		'fieldid' => 377,
		'modelid' => 28,
		'field' => 'areaid',
		'name' => '地区',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'areaid',
		'setting' => 'Array
	(
	\'items\' => \'\',
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 3,
		'disabled' => 1
		),
	'title' => Array
		(
		'fieldid' => 378,
		'modelid' => 28,
		'field' => 'title',
		'name' => '专题名称',
		'tips' => '',
		'css' => 'inputtitle',
		'minlength' => 1,
		'maxlength' => 80,
		'pattern' => '',
		'errortips' => '标题字符长度必须为1到80位！',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 80,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => 'onBlur="$.post(\'/modules/news/admin/?ac=content&ajax_request=1\', { op : \'dict_word\',data:$(\'#title\').val()}, function(data){if(data && $(\'#keywords\').val()==\'\') $(\'#keywords\').val(data); })" ',
		'forminfo' => '  <input type="button" value="检测专题是否已存在" onclick="$.post(\'/modules/news/admin/?ac=content&ajax_request=1\', { op : \'check_title\',c_title:$(\'#title\').val(),catid:$(\'#catid\').val()}, function(data){ $(\'#t_msg\').html(data); })">&nbsp;<span style="color:\'#ff0000\'" id=\'t_msg\'></span>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 4,
		'disabled' => '0'
		),
	'style' => Array
		(
		'fieldid' => 379,
		'modelid' => 28,
		'field' => 'style',
		'name' => '颜色和字型',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'hidden',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => ' <select name="style_color1" id="style_color1" onchange="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value +=  \' \'+document.all.style_strong1.value;"><option value="">颜色</option><option value="c1"  class="bg1"></option><option value="c2"  class="bg2"></option><option value="c3"  class="bg3"></option><option value="c4"  class="bg4"></option><option value="c5"  class="bg5"></option><option value="c6"  class="bg6"></option><option value="c7"  class="bg7"></option><option value="c8"  class="bg8"></option><option value="c9"  class="bg9"></option><option value="c10"  class="bg10"></option><option value="c11"  class="bg11"></option><option value="c12"  class="bg12"></option><option value="c13"  class="bg13"></option><option value="c14"  class="bg14"></option><option value="c15"  class="bg15"></option></select><label><input type="checkbox" name="style_strong1" id="style_strong1" value="b" onclick="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value += \' \'+document.all.style_strong1.value;"> 加粗</label><script>if(document.all.style.value!=\'\'){var temp=document.all.style.value;if(temp.indexOf("b")!=-1){document.all.style_strong1.checked=true;}var sint=temp.replace(/[^\\d]*/ig,"");if(sint!=\'\'){document.all.style_color1.selectedIndex = sint;}}</script>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 5,
		'disabled' => '0'
		),
	'thumb' => Array
		(
		'fieldid' => 380,
		'modelid' => 28,
		'field' => 'thumb',
		'name' => '缩略图',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'image',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\',
	\'maxsize\' => \'\',
	\'fileextname\' => \'jpg,jpeg,gif,png,bmp\',
	\'isselectimage\' => 1,
	\'enablesaveimage\' => \'0\',
	\'thumb_enable\' => -1,
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => -1,
	\'attachwimage\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 6,
		'disabled' => '0'
		),
	'specialbanner' => Array
		(
		'fieldid' => 393,
		'modelid' => 28,
		'field' => 'specialbanner',
		'name' => '专题横幅',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'image',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\',
	\'maxsize\' => 2048,
	\'fileextname\' => \'jpg,jpeg,gif,png,bmp\',
	\'isselectimage\' => 1,
	\'enablesaveimage\' => 1,
	\'thumb_enable\' => \'0\',
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => \'0\',
	\'attachwimage\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 6,
		'disabled' => '0'
		),
	'keywords' => Array
		(
		'fieldid' => 381,
		'modelid' => 28,
		'field' => 'keywords',
		'name' => '关键词',
		'tips' => '多关键词之间用空格隔开',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '<select name="selectkeywords" onchange="$(\'#keywords\').val($(\'#keywords\').val()+this.value+\' \')" style="width:85px"><option>常用关键词</option></select>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 7,
		'disabled' => '0'
		),
	'description' => Array
		(
		'fieldid' => 382,
		'modelid' => 28,
		'field' => 'description',
		'name' => '专题摘要',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'textarea',
		'setting' => 'Array
	(
	\'rows\' => 4,
	\'cols\' => 50,
	\'defaultvalue\' => \'\',
	\'enablehtml\' => 1
	)',
		'formattribute' => 'style="width:80%" onkeyup="checkLength(this, \'description\', \'255\');"',
		'forminfo' => ' <br /><img src="/modules/news/images/icon.gif" width="12"> 还可以输入 <font id="ls_description" color="#ff0000;">255</font> 个字符！',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 8,
		'disabled' => '0'
		),
	'userid' => Array
		(
		'fieldid' => 386,
		'modelid' => 28,
		'field' => 'userid',
		'name' => '发布人',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'userid',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 9,
		'disabled' => '0'
		),
	'meta_title' => Array
		(
		'fieldid' => 396,
		'modelid' => 28,
		'field' => 'meta_title',
		'name' => '网页标题',
		'tips' => '网页title，针对搜索引擎优化！',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 80,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => 1,
		'listorder' => 10,
		'disabled' => '0'
		),
	'meta_keywords' => Array
		(
		'fieldid' => 397,
		'modelid' => 28,
		'field' => 'meta_keywords',
		'name' => '网页关键词',
		'tips' => '网页meta_keywords，针对搜索引擎优化！',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 80,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => 1,
		'listorder' => 10,
		'disabled' => '0'
		),
	'meta_description' => Array
		(
		'fieldid' => 398,
		'modelid' => 28,
		'field' => 'meta_description',
		'name' => '网页描述',
		'tips' => '网页meta_description，针对搜索引擎优化！',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'textarea',
		'setting' => 'Array
	(
	\'rows\' => 5,
	\'cols\' => 60,
	\'defaultvalue\' => \'\',
	\'enablehtml\' => \'0\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => 1,
		'listorder' => 10,
		'disabled' => '0'
		),
	'updatetime' => Array
		(
		'fieldid' => 387,
		'modelid' => 28,
		'field' => 'updatetime',
		'name' => '更新时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 10,
		'disabled' => '0'
		),
	'content' => Array
		(
		'fieldid' => 392,
		'modelid' => 28,
		'field' => 'content',
		'name' => '专题简介',
		'tips' => '<label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取专题简介</label><br><input type="text" name="introcude_length" value="200" size="3">字符至专题摘要
<br/><br/>
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1" checked>是否获取专题简介第</label><br><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为专题图片',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 999999,
		'pattern' => '',
		'errortips' => '请填写文章内容！',
		'formtype' => 'editor',
		'setting' => 'Array
	(
	\'toolbar\' => \'basic\',
	\'width\' => \'100%\',
	\'height\' => 250,
	\'defaultvalue\' => \'\',
	\'openpagetag\' => \'0\',
	\'storage\' => \'database\',
	\'thumb_enable\' => -1,
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => -1,
	\'attachwimage\' => \'\',
	\'enablereplaceurls\' => 1,
	\'enablesaveimage\' => 1,
	\'enablesaveflash\' => \'0\',
	\'savefileext\' => \'mp3|rar|zip\',
	\'forbidwords\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 11,
		'disabled' => 1
		),
	'vars' => Array
		(
		'fieldid' => 394,
		'modelid' => 28,
		'field' => 'vars',
		'name' => '动态变量',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'vars',
		'setting' => 'Array
	(
	\'enablehtml\' => 1,
	\'vars\' => Array
		(
		\'图片推荐\' => \'这里是默认的图片推荐‘“;\\\'"\',
		\'图文推荐\' => \'这里是默认的图文推荐‘“;\\\'"\',
		\'顶部推荐\' => \'顶部推荐测试\'
		)
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => 1,
		'listorder' => 11,
		'disabled' => '0'
		),
	's_news' => Array
		(
		'fieldid' => 419,
		'modelid' => 28,
		'field' => 's_news',
		'name' => '游戏资讯',
		'tips' => '动态区块',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 1000,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'find',
		'setting' => 'Array
	(
	\'blocknum\' => 20,
	\'pagesize\' => 25,
	\'maxpage\' => 20,
	\'listtemplate\' => \'taglist.html\',
	\'urlrule\' => \'news/{$page}\',
	\'fields\' => Array
		(
		\'catid\' => Array
			(
			\'name\' => \'栏 目\',
			\'where\' => \'\'
			),
		\'title\' => Array
			(
			\'name\' => \'标 题\',
			\'where\' => \'\'
			),
		\'keywords\' => Array
			(
			\'name\' => \'关键词\',
			\'where\' => \'\'
			)
		)
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 11,
		'disabled' => '0'
		),
	's_gl' => Array
		(
		'fieldid' => 420,
		'modelid' => 28,
		'field' => 's_gl',
		'name' => '专题攻略',
		'tips' => '专题攻略列表',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 1000,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'find',
		'setting' => 'Array
	(
	\'blocknum\' => 15,
	\'pagesize\' => 25,
	\'maxpage\' => 20,
	\'listtemplate\' => \'taglist.html\',
	\'urlrule\' => \'gl/{$page}.html\',
	\'fields\' => Array
		(
		\'catid\' => Array
			(
			\'name\' => \'栏 目\',
			\'where\' => \'\'
			),
		\'title\' => Array
			(
			\'name\' => \'标 题\',
			\'where\' => \'\'
			),
		\'keywords\' => Array
			(
			\'name\' => \'关键词\',
			\'where\' => \'\'
			)
		)
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 11,
		'disabled' => '0'
		),
	'url' => Array
		(
		'fieldid' => 385,
		'modelid' => 28,
		'field' => 'url',
		'name' => '转向链接',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => 'readonly',
		'forminfo' => '  <font color="#FF0000"><label><input type="checkbox" id="linkurl" value="1" onclick="javascript:if(this.checked==true) $(\'#url\').attr(\'readonly\',\'\');else $(\'#url\').attr(\'readonly\',\'true\');" > 转向链接</label></font><br/><font color="#FF0000">如果使用转向链接则点击标题就直接跳转而内容设置无效</font>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 12,
		'disabled' => '0'
		),
	'inputtime' => Array
		(
		'fieldid' => 388,
		'modelid' => 28,
		'field' => 'inputtime',
		'name' => '发布时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'Array
	(
	\'format\' => \'Y-m-d H:i:s\',
	\'defaulttype\' => 1,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 13,
		'disabled' => '0'
		),
	'posids' => Array
		(
		'fieldid' => 383,
		'modelid' => 28,
		'field' => 'posids',
		'name' => '推荐位',
		'tips' => '全选<input boxid=\'posids\' type=\'checkbox\' onclick="checkall(\'posids\')" >',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'posid',
		'setting' => 'Array
	(

	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 14,
		'disabled' => '0'
		),
	'listorder' => Array
		(
		'fieldid' => 384,
		'modelid' => 28,
		'field' => 'listorder',
		'name' => '排序',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 1,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 97,
		'disabled' => '0'
		),
	'status' => Array
		(
		'fieldid' => 390,
		'modelid' => 28,
		'field' => 'status',
		'name' => '状态',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 2,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 98,
		'disabled' => '0'
		),
	'template' => Array
		(
		'fieldid' => 391,
		'modelid' => 28,
		'field' => 'template',
		'name' => '专题页模板',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 50,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'template',
		'setting' => 'Array
	(
	\'items\' => \'\',
	\'size\' => 1,
	\'defaultvalue\' => \'\',
	\'multiple\' => \'0\',
	\'fieldtype\' => \'CHAR\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 99,
		'disabled' => '0'
		),
	't_style' => Array
		(
		'fieldid' => 395,
		'modelid' => 28,
		'field' => 't_style',
		'name' => '模板风格',
		'tips' => '填写存在的风格样式控制模板显示风格',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 20,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 12,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '可供选择[purple|blue|green],默认为purple',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 99,
		'disabled' => '0'
		),
	'prefix' => Array
		(
		'fieldid' => 389,
		'modelid' => 28,
		'field' => 'prefix',
		'name' => '专题页文件名',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 30,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 20,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => ' 默认扩展名为：<font color="#ff0000">.html</font>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 100,
		'disabled' => '0'
		)
	)
?>