<?php
if(!defined('IN_JQNEWS')) exit('Access Denied');
$_SGLOBAL['model_31_field']=Array
	(
	'contentid' => Array
		(
		'fieldid' => 444,
		'modelid' => 31,
		'field' => 'contentid',
		'name' => 'ID',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => 1,
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => '0',
		'disabled' => '0'
		),
	'catid' => Array
		(
		'fieldid' => 445,
		'modelid' => 31,
		'field' => 'catid',
		'name' => '栏目',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 9999,
		'pattern' => '/^[0-9]+$/',
		'errortips' => '请选择所属栏目',
		'formtype' => 'catid',
		'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 1,
		'disabled' => '0'
		),
	'typeid' => Array
		(
		'fieldid' => 446,
		'modelid' => 31,
		'field' => 'typeid',
		'name' => '类别',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'typeid',
		'setting' => 'array (
  \'minnumber\' => \'\',
  \'maxnumber\' => \'\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 2,
		'disabled' => '0'
		),
	'areaid' => Array
		(
		'fieldid' => 447,
		'modelid' => 31,
		'field' => 'areaid',
		'name' => '地区',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'areaid',
		'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 3,
		'disabled' => '0'
		),
	'title' => Array
		(
		'fieldid' => 448,
		'modelid' => 31,
		'field' => 'title',
		'name' => '标题',
		'tips' => '',
		'css' => 'inputtitle',
		'minlength' => 1,
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '标题字符长度必须为1到100位！',
		'formtype' => 'text',
		'setting' => 'Array
	(
	\'size\' => 80,
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => 'onBlur="$.post(\'/modules/news/admin/?ac=content&ajax_request=1\', { op : \'dict_word\',data:$(\'#title\').val(),catid:$(\'#catid\').val()}, function(data){if(data && $(\'#keywords\').val()==\'\') $(\'#keywords\').val(data); })" ',
		'forminfo' => '  <input type="button" value="检测标题是否已存在" onclick="$.post(\'/modules/news/admin/?ac=content&ajax_request=1\', { op : \'check_title\',title:$(\'#title\').val()}, function(data){ $(\'#t_msg\').html(data); })">&nbsp;<span style="color:\'#ff0000\'" id=\'t_msg\'></span>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 4,
		'disabled' => '0'
		),
	'style' => Array
		(
		'fieldid' => 449,
		'modelid' => 31,
		'field' => 'style',
		'name' => '颜色和字型',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'hidden',
		'setting' => 'Array
	(
	\'defaultvalue\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => ' <select name="style_color1" id="style_color1" onchange="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value +=  \' \'+document.all.style_strong1.value;"><option value="">颜色</option><option value="c1"  class="bg1"></option><option value="c2"  class="bg2"></option><option value="c3"  class="bg3"></option><option value="c4"  class="bg4"></option><option value="c5"  class="bg5"></option><option value="c6"  class="bg6"></option><option value="c7"  class="bg7"></option><option value="c8"  class="bg8"></option><option value="c9"  class="bg9"></option><option value="c10"  class="bg10"></option><option value="c11"  class="bg11"></option><option value="c12"  class="bg12"></option><option value="c13"  class="bg13"></option><option value="c14"  class="bg14"></option><option value="c15"  class="bg15"></option></select><label><input type="checkbox" name="style_strong1" id="style_strong1" value="b" onclick="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value += \' \'+document.all.style_strong1.value;"> 加粗</label><script>if(document.all.style.value!=\'\'){var temp=document.all.style.value;if(temp.indexOf("b")!=-1){document.all.style_strong1.checked=true;}var sint=temp.replace(/[^\\d]*/ig,"");if(sint!=\'\'){document.all.style_color1.selectedIndex = sint;}}</script>',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 5,
		'disabled' => '0'
		),
	'thumb' => Array
		(
		'fieldid' => 450,
		'modelid' => 31,
		'field' => 'thumb',
		'name' => '缩略图',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'image',
		'setting' => 'Array
	(
	\'size\' => 50,
	\'defaultvalue\' => \'\',
	\'maxsize\' => \'\',
	\'fileextname\' => \'jpg,jpeg,gif,png,bmp\',
	\'isselectimage\' => 1,
	\'thumb_enable\' => -1,
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => -1,
	\'attachwimage\' => \'\'
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 6,
		'disabled' => '0'
		),
	'keywords' => Array
		(
		'fieldid' => 451,
		'modelid' => 31,
		'field' => 'keywords',
		'name' => '关键词',
		'tips' => '多关键词之间用空格隔开',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 100,
		'pattern' => '',
		'errortips' => '关键词字符长度必须为1到100位！',
		'formtype' => 'text',
		'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '<select name="selectkeywords" onchange="$(\'#keywords\').val($(\'#keywords\').val()+this.value+\' \')" style="width:85px"><option>常用关键词</option></select>',
		'unsetgroupids' => -99,
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 7,
		'disabled' => '0'
		),
	'description' => Array
		(
		'fieldid' => 452,
		'modelid' => 31,
		'field' => 'description',
		'name' => '摘要',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 255,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'textarea',
		'setting' => 'Array
	(
	\'rows\' => 4,
	\'cols\' => 50,
	\'defaultvalue\' => \'\',
	\'enablehtml\' => 1
	)',
		'formattribute' => 'style="width:80%" onkeyup="checkLength(this, \'description\', \'255\');"',
		'forminfo' => ' <br /><img src="/modules/news/images/icon.gif" width="12"> 还可以输入 <font id="ls_description" color="#ff0000;">255</font> 个字符！',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => 1,
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 8,
		'disabled' => '0'
		),
	'videos' => Array
		(
		'fieldid' => 464,
		'modelid' => 31,
		'field' => 'videos',
		'name' => '视频ddddd',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'video',
		'setting' => 'Array
	(

	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 9,
		'disabled' => '0'
		),
	'userid' => Array
		(
		'fieldid' => 456,
		'modelid' => 31,
		'field' => 'userid',
		'name' => '发布人',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'userid',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 9,
		'disabled' => '0'
		),
	'updatetime' => Array
		(
		'fieldid' => 457,
		'modelid' => 31,
		'field' => 'updatetime',
		'name' => '更新时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 10,
		'disabled' => '0'
		),
	'content' => Array
		(
		'fieldid' => 462,
		'modelid' => 31,
		'field' => 'content',
		'name' => '内容',
		'tips' => '<label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><br><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要
<br/><br/>
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1" checked>是否获取内容第</label><br><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 999999,
		'pattern' => '',
		'errortips' => '请填写文章内容！',
		'formtype' => 'editor',
		'setting' => 'Array
	(
	\'toolbar\' => \'standard\',
	\'width\' => \'100%\',
	\'height\' => 350,
	\'defaultvalue\' => \'\',
	\'storage\' => \'database\',
	\'thumb_enable\' => -1,
	\'thumb_width\' => \'\',
	\'thumb_height\' => \'\',
	\'attachwater\' => -1,
	\'attachwimage\' => \'\',
	\'enablesaveimage\' => 1
	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => 1,
		'isselect' => 1,
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => 1,
		'listorder' => 11,
		'disabled' => '0'
		),
	'url' => Array
		(
		'fieldid' => 455,
		'modelid' => 31,
		'field' => 'url',
		'name' => '转向链接',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => 'readonly',
		'forminfo' => '  <font color="#FF0000"><label><input type="checkbox" id="linkurl" value="1" onclick="javascript:if(this.checked==true) $(\'#url\').attr(\'readonly\',\'\');else $(\'#url\').attr(\'readonly\',\'true\');" > 转向链接</label></font><br/><font color="#FF0000">如果使用转向链接则点击标题就直接跳转而内容设置无效</font>',
		'unsetgroupids' => -99,
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => 1,
		'isshow' => 1,
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 12,
		'disabled' => '0'
		),
	'inputtime' => Array
		(
		'fieldid' => 458,
		'modelid' => 31,
		'field' => 'inputtime',
		'name' => '发布时间',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'datetime',
		'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 13,
		'disabled' => '0'
		),
	'posids' => Array
		(
		'fieldid' => 453,
		'modelid' => 31,
		'field' => 'posids',
		'name' => '推荐位',
		'tips' => '全选<input boxid=\'posids\' type=\'checkbox\' onclick="checkall(\'posids\')" >',
		'css' => '',
		'minlength' => '0',
		'maxlength' => '0',
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'posid',
		'setting' => 'Array
	(

	)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 14,
		'disabled' => '0'
		),
	'prefix' => Array
		(
		'fieldid' => 459,
		'modelid' => 31,
		'field' => 'prefix',
		'name' => 'html文件名',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 50,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'text',
		'setting' => 'array (
  \'size\' => \'12\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => -99,
		'iscore' => '0',
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 19,
		'disabled' => '0'
		),
	'listorder' => Array
		(
		'fieldid' => 454,
		'modelid' => 31,
		'field' => 'listorder',
		'name' => '排序',
		'tips' => '',
		'css' => '',
		'minlength' => 1,
		'maxlength' => 1,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => 1,
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 97,
		'disabled' => '0'
		),
	'status' => Array
		(
		'fieldid' => 460,
		'modelid' => 31,
		'field' => 'status',
		'name' => '状态',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 2,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'number',
		'setting' => '',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => 1,
		'issystem' => 1,
		'isunique' => '0',
		'isbase' => 1,
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => 1,
		'isfulltext' => '0',
		'listorder' => 98,
		'disabled' => '0'
		),
	'template' => Array
		(
		'fieldid' => 461,
		'modelid' => 31,
		'field' => 'template',
		'name' => '内容页模板',
		'tips' => '',
		'css' => '',
		'minlength' => '0',
		'maxlength' => 50,
		'pattern' => '',
		'errortips' => '',
		'formtype' => 'template',
		'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
)',
		'formattribute' => '',
		'forminfo' => '',
		'unsetgroupids' => '',
		'iscore' => '0',
		'issystem' => '0',
		'isunique' => '0',
		'isbase' => '0',
		'issearch' => '0',
		'isselect' => '0',
		'isorder' => '0',
		'islist' => '0',
		'isshow' => '0',
		'isadd' => '0',
		'isfulltext' => '0',
		'listorder' => 99,
		'disabled' => '0'
		)
	)
?>