CREATE TABLE `$tablename` (
  `contentid` MEDIUMINT(8) unsigned NOT NULL,
  `template` char(30) NOT NULL,
  `content` mediumtext NOT NULL,
  PRIMARY KEY  (`contentid`)
) TYPE=MyISAM;

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'contentid', 'ID', '', '', 0, 0, '', '', 'number', '', '',  '', 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'catid', '栏目', '', '', 1, 9999, '/^[0-9]+$/', '请选择所属栏目', 'catid', 'array (\n  ''defaultvalue'' => '''',\n)', '', '',  0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'typeid', '类别', '', '', 0, 0, '', '', 'typeid', 'array (\n  ''minnumber'' => '''',\n  ''maxnumber'' => '''',\n  ''defaultvalue'' => '''',\n)', '', '',  0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'areaid', '地区', '', '', 0, 0, '', '', 'areaid', 'array (\n  ''defaultvalue'' => '''',\n)', '', '',  0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 3, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'title', '标题', '', 'inputtitle', 1, 100, '', '标题字符长度必须为1到100位！', 'text', 'Array\n	(\n	''size'' => 80,\n	''defaultvalue'' => ''''\n	)','onBlur="$.post(''/modules/news/admin/?ac=content&ajax_request=1'', { op : ''dict_word'',data:$(''#title'').val(),catid:$(''#catid'').val()}, function(data){if(data && $(''#keywords'').val()=='''') $(''#keywords'').val(data); })" ', '  <input type="button" value="检测标题是否已存在" onclick="$.post(''/modules/news/admin/?ac=content&ajax_request=1'', { op : ''check_title'',title:$(''#title'').val()}, function(data){ $(''#t_msg'').html(data); })">&nbsp;<span style="color:''#ff0000''" id=''t_msg''></span>', '', 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 4, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'style', '颜色和字型', '', '', 0, 0, '', '', 'hidden', 'Array\r\n	(\r\n	''defaultvalue'' => ''''\r\n	)', '', ' <select name="style_color1" id="style_color1" onchange="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value +=  '' ''+document.all.style_strong1.value;"><option value="">颜色</option><option value="c1"  class="bg1"></option><option value="c2"  class="bg2"></option><option value="c3"  class="bg3"></option><option value="c4"  class="bg4"></option><option value="c5"  class="bg5"></option><option value="c6"  class="bg6"></option><option value="c7"  class="bg7"></option><option value="c8"  class="bg8"></option><option value="c9"  class="bg9"></option><option value="c10"  class="bg10"></option><option value="c11"  class="bg11"></option><option value="c12"  class="bg12"></option><option value="c13"  class="bg13"></option><option value="c14"  class="bg14"></option><option value="c15"  class="bg15"></option></select><label><input type="checkbox" name="style_strong1" id="style_strong1" value="b" onclick="document.all.style.value=document.all.style_color1.value;if(document.all.style_strong1.checked)document.all.style.value += '' ''+document.all.style_strong1.value;"> 加粗</label><script>if(document.all.style.value!=''''){var temp=document.all.style.value;if(temp.indexOf("b")!=-1){document.all.style_strong1.checked=true;}var sint=temp.replace(/[^\\d]*/ig,"");if(sint!=''''){document.all.style_color1.selectedIndex = sint;}}</script>', '', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 5, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'thumb', '缩略图', '', '', 0, 100, '', '', 'image', 'Array\n	(\n	''size'' => 50,\n	''defaultvalue'' => '''',\n	''maxsize'' => '''',\n	''fileextname'' => ''jpg,jpeg,gif,png,bmp'',\n	''isselectimage'' => 1,\n	''thumb_enable'' => -1,\n	''thumb_width'' => '''',\n	''thumb_height'' => '''',\n	''attachwater'' => -1,\n	''attachwimage'' => ''''\n	)', '', '', '', 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 6, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'keywords', '关键词', '多关键词之间用空格隔开', '', 0, 100, '', '关键词字符长度必须为1到100位！', 'text', 'array (\r\n  ''size'' => ''50'',\r\n  ''defaultvalue'' => '''',\r\n)', '', '<select name="selectkeywords" onchange="$(''#keywords'').val($(''#keywords'').val()+this.value+'' '')" style="width:85px"><option>常用关键词</option></select>', '-99', 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 7, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'description', '摘要', '', '', 0, 255, '', '', 'textarea', 'Array\r\n	(\r\n	''rows'' => 4,\r\n	''cols'' => 50,\r\n	''defaultvalue'' => '''',\r\n	''enablehtml'' => 1\r\n	)', 'style="width:80%" onkeyup="checkLength(this, ''description'', ''255'');"', ' <br /><img src="/modules/news/images/icon.gif" width="12"> 还可以输入 <font id="ls_description" color="#ff0000;">255</font> 个字符！', '', 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 8, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'posids', '推荐位', '全选<input boxid=''posids'' type=''checkbox'' onclick="checkall(''posids'')" >', '', 0, 0, '', '', 'posid', 'Array\n	(\n\n	)', '', '', '', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'listorder', '排序', '', '', 1, 1, '', '', 'number', '', '',  '', 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 97, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'url', '转向链接', '', '', 0, 0, '', '', 'text', 'array (\r\n  ''size'' => ''50'',\r\n  ''defaultvalue'' => '''',\r\n)', 'readonly', '  <font color="#FF0000"><label><input type="checkbox" id="linkurl" value="1" onclick="javascript:if(this.checked==true) $(''#url'').attr(''readonly'','''');else $(''#url'').attr(''readonly'',''true'');" > 转向链接</label></font><br/><font color="#FF0000">如果使用转向链接则点击标题就直接跳转而内容设置无效</font>', '-99', 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 12, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'userid', '发布人', '', '', 0, 0, '', '', 'userid', '', '',  '', 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 9, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'updatetime', '更新时间', '', '', 0, 0, '', '', 'datetime', 'array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)', '', '',  1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 10, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'inputtime', '发布时间', '', '', 0, 0, '', '', 'datetime', 'array (\r\n  ''dateformat'' => ''int'',\r\n  ''format'' => ''Y-m-d H:i:s'',\r\n  ''defaulttype'' => ''1'',\r\n  ''defaultvalue'' => '''',\r\n)', '', '',  0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 13, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'prefix', 'html文件名', '', '', 0, 50, '', '', 'text', 'array (\n  ''size'' => ''12'',\n  ''defaultvalue'' => '''',\n)', '', '-99', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'status', '状态', '', '', 0, 2, '', '', 'number', '', '',  '', 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 98, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'template', '内容页模板', '', '', 0, 50, '', '', 'template', 'array (\r\n  ''size'' => '''',\r\n  ''defaultvalue'' => '''',\r\n)', '',  '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0);

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `forminfo`, `unsetgroupids`, `iscore`, `issystem`, `isunique`, `isbase`, `issearch`, `isselect`, `isorder`, `islist`, `isshow`, `isadd`, `isfulltext`, `listorder`, `disabled`) VALUES ($modelid, 'content', '内容', '<label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><br><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要\r\n<br/><br/>\r\n<label><input type=''checkbox'' name=''auto_thumb'' value="1" checked>是否获取内容第</label><br><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片', '', 1, 999999, '', '请填写文章内容！', 'editor', 'Array\n	(\n	''toolbar'' => ''standard'',\n	''width'' => ''100%'',\n	''height'' => 350,\n	''defaultvalue'' => '''',\n	''storage'' => ''database'',\n	''thumb_enable'' => -1,\n	''thumb_width'' => '''',\n	''thumb_height'' => '''',\n	''attachwater'' => -1,\n	''attachwimage'' => '''',\n	''enablesaveimage'' => 1\n	)', '', '', '', 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 11, 0);
