<?php
$jieqiCollect['sitename'] = 'haokan5.com';
$jieqiCollect['siteurl'] = 'http://www.haokan5.com';
$jieqiCollect['subarticleid'] = 'floor($articleid / 1000)';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '0';
$jieqiCollect['autochaptercollect'] = '1';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '1';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = 'makehtml,makezip,maketxtfull,makeumd,makejar';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://www.haokan5.com/show/<{articleid}>.html';
$jieqiCollect['articletitle']['left'] = 'name:\'';
$jieqiCollect['articletitle']['right'] = '\',';
$jieqiCollect['articletitle']['middle'] = '~~~~';
$jieqiCollect['author']['left'] = '作者：<a href="/search.asp?searchword=~">';
$jieqiCollect['author']['right'] = '</a>';
$jieqiCollect['author']['middle'] = '~~~~';
$jieqiCollect['sort']['left'] = '类型：</b>';
$jieqiCollect['sort']['right'] = '</p><p><b>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type']['left'] = '<li class="tab"><b>标签:</b>';
$jieqiCollect['type']['right'] = '</li>!</ul>!</div>!<div itemprop="newestChapter" itemscope itemtype';
$jieqiCollect['type']['middle'] = '****';
$jieqiCollect['keyword']['left'] = '<li class="tab"><b>标签:</b>';
$jieqiCollect['keyword']['right'] = '</li>!</ul>!</div>!<div itemprop="newestChapter" itemscope itemtype';
$jieqiCollect['keyword']['middle'] = '****';
$jieqiCollect['intro']['left'] = 'class="introbox"><p>';
$jieqiCollect['intro']['right'] = '<font color="#666666">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<img class="imgd" src="';
$jieqiCollect['articleimage']['right'] = '" alt="~" />';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = 'http://www.haokan5.com/pic/nopic.gif';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '<b>状态：</b>完结</b>';
$jieqiCollect['sortid']['玄幻'] = '1';
$jieqiCollect['sortid']['武侠'] = '6';
$jieqiCollect['sortid']['都市'] = '2';
$jieqiCollect['sortid']['言情'] = '12';
$jieqiCollect['sortid']['女生'] = '101';
$jieqiCollect['sortid']['科幻'] = '5';
$jieqiCollect['sortid']['恐怖'] = '10';
$jieqiCollect['sortid']['惊悚'] = '10';
$jieqiCollect['sortid']['历史'] = '8';
$jieqiCollect['sortid']['军事'] = '9';
$jieqiCollect['sortid']['网游'] = '4';
$jieqiCollect['sortid']['推理'] = '10';
$jieqiCollect['sortid']['评书'] = '207';
$jieqiCollect['sortid']['相声'] = '209';
$jieqiCollect['sortid']['儿童'] = '203';
$jieqiCollect['sortid']['百家讲坛'] = '204';
$jieqiCollect['sortid']['default'] = '1';
$jieqiCollect['urlindex'] = 'http://www.haokan5.com/show/<{articleid}>.html';
$jieqiCollect['volume'] = '';
$jieqiCollect['chapter']['left'] = '<a href=\'/down/?$-$.html\' target="_self">';
$jieqiCollect['chapter']['right'] = '</a>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<a href=\'/down/?$-';
$jieqiCollect['chapterid']['right'] = '.html\' target="_self">!</a>';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '作品相关';
$jieqiCollect['urlchapter'] = 'http://www.haokan5.com/down/?<{articleid}>-<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<a class="dlink" title="1号线路" href="';
$jieqiCollect['content']['right'] = '">本地1线</a>';
$jieqiCollect['content']['middle'] = '~~~~';
$jieqiCollect['contentfilter'] = '';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect'] = '';

?>