<?php
$jieqiCollect['sitename'] = '17k.com';
$jieqiCollect['siteurl'] = 'http://www.17k.com';
$jieqiCollect['subarticleid'] = 'floor($articleid / 1000)';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '0';
$jieqiCollect['autochaptercollect'] = '1';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '1';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = 'makehtml';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://www.17k.com/book/<{articleid}>.html';
$jieqiCollect['articletitle']['left'] = 'var bookName = "';
$jieqiCollect['articletitle']['right'] = '";';
$jieqiCollect['articletitle']['middle'] = '~~~~';
$jieqiCollect['author']['left'] = 'var authorPenname = "';
$jieqiCollect['author']['right'] = '";';
$jieqiCollect['author']['middle'] = '~~~~';
$jieqiCollect['sort']['left'] = '<a href="http://~.17k.com/~/" target="_blank">';
$jieqiCollect['sort']['right'] = '</a> &gt;&gt;';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword']['left'] = '<li class="tab"><b>标签:</b>';
$jieqiCollect['keyword']['right'] = '</li>!</ul>!</div>!<div itemprop="newestChapter" itemscope itemtype';
$jieqiCollect['keyword']['middle'] = '****';
$jieqiCollect['intro']['left'] = '<font itemprop="description">';
$jieqiCollect['intro']['right'] = '</font></a></p>!</div>!<div class="c6" id="tab91_div1" style="display:none;">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<a href="/list/$.html" target="_blank"><img itemprop="image" src="';
$jieqiCollect['articleimage']['right'] = '" alt="~" /></a>';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = 'http://img.17k.com/images/bookcover/default_cover2.jpg';
$jieqiCollect['indexlink']['left'] = 'var bookId=';
$jieqiCollect['indexlink']['right'] = ';';
$jieqiCollect['indexlink']['middle'] = '$$$$';
$jieqiCollect['fullarticle'] = '此书已完成';
$jieqiCollect['sortid']['玄幻'] = '1';
$jieqiCollect['sortid']['武侠'] = '4';
$jieqiCollect['sortid']['都市'] = '2';
$jieqiCollect['sortid']['女生'] = '13';
$jieqiCollect['sortid']['游戏'] = '9';
$jieqiCollect['sortid']['穿越小说'] = '5';
$jieqiCollect['sortid']['军事'] = '7';
$jieqiCollect['sortid']['科幻'] = '8';
$jieqiCollect['sortid']['default'] = '2';
$jieqiCollect['urlindex'] = 'http://www.17k.com/list/<{indexlink}>.html';
$jieqiCollect['volume']['left'] = '<div class="tit">!<h2>';
$jieqiCollect['volume']['right'] = '</h2>!<span class="c12">';
$jieqiCollect['volume']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = '<a id="tips_$" tn="~" tw="$" td="~" target="_blank" href="/chapter/$/$.html"  >';
$jieqiCollect['chapter']['right'] = '</a>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<a id="tips_';
$jieqiCollect['chapterid']['right'] = '" tn="~" tw="$" td="~" target="_blank" href="/chapter/$/$.html"  >!</a>';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '作品相关';
$jieqiCollect['urlchapter'] = 'http://www.17k.com/chapter/<{articleid}>/<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<div id="chapterContentWapper">';
$jieqiCollect['content']['right'] = '</div>!<!-- 作者有话说';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = '';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '书库列表';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://all.17k.com/all/0_0__0__<{pageid}>.html';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<td class="~"><span><a class="jt" rel="~"  href="http://www.17k.com/book/';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '.html" target="_blank">!</a>';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '';

?>