<?php
$jieqiCollect['sitename'] = '随便看看-名著';
$jieqiCollect['siteurl'] = 'http://www.sbkk8.cn';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '1';
$jieqiCollect['referer'] = '1';
$jieqiCollect['autochaptercollect'] = '0';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = 'makehtml';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://www.sbkk8.cn/<{articleid}>/';
$jieqiCollect['articletitle']['left'] = '<a href=\'http://www.sbkk8.cn/\'>主页</a> > <a href=\'/!/!/\'>!</a> > <a href=\'/!/!/!/\'>';
$jieqiCollect['articletitle']['right'] = '</a> >  </div>';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '_小说在线阅读_';
$jieqiCollect['author']['right'] = '</title>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '<a href=\'http://www.sbkk8.cn/\'>主页</a> > <a href=\'!\'>';
$jieqiCollect['sort']['right'] = '</a> >';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['left'] = '<p class="des">';
$jieqiCollect['intro']['right'] = '</div>!</div>!<ul class="leftList">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<div class="ablum"><img src="';
$jieqiCollect['articleimage']['right'] = '" alt=';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = '';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '';
$jieqiCollect['urlindex'] = 'http://www.sbkk8.cn/<{articleid}>/';
$jieqiCollect['volume'] = '';
$jieqiCollect['chapter']['left'] = 'class="articleTitle"  target="_blank">';
$jieqiCollect['chapter']['right'] = '</a> </li>';
$jieqiCollect['chapter']['middle'] = '****';
$jieqiCollect['chapterid']['left'] = '<li> <a href="/!/!/!/';
$jieqiCollect['chapterid']['right'] = '.html" class="articleTitle"  target="_blank"';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '';
$jieqiCollect['urlchapter'] = 'http://www.sbkk8.cn/<{articleid}>//<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script></span>';
$jieqiCollect['content']['right'] = '<ul class="!_page">';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = 'www.sbkk8.cn
sbkk8';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect'] = '';

?>