<?php
$jieqiCollect['sitename'] = '恒言古典频道';
$jieqiCollect['siteurl'] = 'http://gudian.hengyan.com';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '1';
$jieqiCollect['referer'] = '1';
$jieqiCollect['autochaptercollect'] = '1';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '1';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = 'makehtml';
$jieqiCollect['pagecharset'] = 'utf8';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://gudian.hengyan.com/<{articleid}>/book.html';
$jieqiCollect['articletitle']['left'] = '<title>';
$jieqiCollect['articletitle']['right'] = '-在线阅读';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '<meta name="description" content="古典文学网提供作者';
$jieqiCollect['author']['right'] = '的';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '简介,txt全集下载,读后感,';
$jieqiCollect['sort']['right'] = '-古典文学网</title>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['left'] = '<div class="des">';
$jieqiCollect['intro']['right'] = '</div>!</div>!<div class="fx">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<div class="fm">!<img src="';
$jieqiCollect['articleimage']['right'] = '" alt="';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = '';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '';
$jieqiCollect['sortid']['default'] = '201';
$jieqiCollect['urlindex'] = 'http://gudian.hengyan.com/<{articleid}>/dir.html';
$jieqiCollect['volume']['left'] = '<p>';
$jieqiCollect['volume']['right'] = '</p>';
$jieqiCollect['volume']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = 'article_$.html" target="_self">';
$jieqiCollect['chapter']['right'] = '</a></li>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '/article_';
$jieqiCollect['chapterid']['right'] = '.html" target="_self">';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '恒言
hengyan';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = 'hengyan';
$jieqiCollect['urlchapter'] = 'http://gudian.hengyan.com/<{articleid}>/article_<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<div id="content">';
$jieqiCollect['content']['right'] = '<div class="prenext">';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = 'hengyan
恒言中文网';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '古典小说';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://gudian.hengyan.com/xiaoshuo/more.aspx?p=<{pageid}>';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<li><a href="/';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '/book.html" target="_blank">!</a></li>';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '!!!!';
$jieqiCollect['listcollect']['0']['startpageid'] = '1';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '7';

?>