<?php
$jieqiCollect['sitename'] = '风起小说旧版';
$jieqiCollect['siteurl'] = 'http://old.fengqiyc.com/';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '0';
$jieqiCollect['autochaptercollect'] = '0';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = '';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://old.fengqiyc.com/archive.php?aid=<{articleid}>';
$jieqiCollect['articletitle']['left'] = '<title>';
$jieqiCollect['articletitle']['right'] = '&mdash;风起中文网';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '<div style="margin:5px;width:100px;float:left;"><a href="http://old.fengqiyc.com/mspace/index.php?mid=$" target="_blank">';
$jieqiCollect['author']['right'] = '</a></div>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '&nbsp;> <a href="http://old.fengqiyc.com/list.php?caid=$">';
$jieqiCollect['sort']['right'] = '</a>&nbsp;>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['left'] = '<div class="list_content">';
$jieqiCollect['intro']['right'] = '</p></div>!<scrip';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<div class="img">!<img src="';
$jieqiCollect['articleimage']['right'] = '" width="215" height="284" />!</div>';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = '';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '';
$jieqiCollect['sortid']['玄幻修真'] = '1';
$jieqiCollect['sortid']['都市异能'] = '2';
$jieqiCollect['sortid']['惊悚悬疑'] = '3';
$jieqiCollect['sortid']['网游娱乐'] = '4';
$jieqiCollect['sortid']['灵界魔法'] = '5';
$jieqiCollect['sortid']['武侠仙缘'] = '6';
$jieqiCollect['sortid']['官场商战'] = '7';
$jieqiCollect['sortid']['军事历史'] = '8';
$jieqiCollect['sortid']['青春校园'] = '101';
$jieqiCollect['sortid']['婚恋家庭'] = '102';
$jieqiCollect['sortid']['穿越架空'] = '103';
$jieqiCollect['sortid']['职场丽人'] = '104';
$jieqiCollect['sortid']['幻情后宫'] = '105';
$jieqiCollect['sortid']['耽美同人'] = '106';
$jieqiCollect['sortid']['总裁豪门'] = '107';
$jieqiCollect['sortid']['都市高干'] = '108';
$jieqiCollect['sortid']['现代诗'] = '201';
$jieqiCollect['sortid']['古体诗'] = '202';
$jieqiCollect['sortid']['散文诗'] = '203';
$jieqiCollect['sortid']['新歌词'] = '204';
$jieqiCollect['sortid']['散文'] = '205';
$jieqiCollect['sortid']['随笔'] = '206';
$jieqiCollect['sortid']['小说'] = '207';
$jieqiCollect['sortid']['杂文'] = '208';
$jieqiCollect['sortid']['诗歌库'] = '209';
$jieqiCollect['sortid']['default'] = '2';
$jieqiCollect['urlindex'] = 'http://old.fengqiyc.com/archive.php?aid=<{articleid}>&addno=1';
$jieqiCollect['volume']['left'] = '<div style="float:left;font-size:14px;margin-top:5px;vertical-align:middle;">';
$jieqiCollect['volume']['right'] = '</div>';
$jieqiCollect['volume']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = '<li><a href="http://old.fengqiyc.com/archive.php?aid=$">';
$jieqiCollect['chapter']['right'] = '</a><span>!</span></li>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<li><a href="http://old.fengqiyc.com/archive.php?aid=';
$jieqiCollect['chapterid']['right'] = '">!</a><span>!</span></li>';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '';
$jieqiCollect['urlchapter'] = 'http://old.fengqiyc.com/archive.php?aid=<{chapterid}>';
$jieqiCollect['content']['left'] = '<div id="htmlContent">';
$jieqiCollect['content']['right'] = '</div>!<div class="s_content">个人评语：';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = '';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '男生最新更新';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://old.fengqiyc.com/list.php?caid=1&page=<{pageid}>';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<div class="b1"><a href="http://old.fengqiyc.com/archive.php?aid=';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '">';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '1';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '320';

?>