<?php
$jieqiCollect['sitename'] = '¹ÅÁúÎäÏÀÐ¡Ëµ';
$jieqiCollect['siteurl'] = 'http://www.gulongbbs.com/';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '1';
$jieqiCollect['referer'] = '1';
$jieqiCollect['autochaptercollect'] = '0';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = '';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = '<{articleid}>';
$jieqiCollect['articletitle']['left'] = '<div align="center" class="STYLE17">!¡¶';
$jieqiCollect['articletitle']['right'] = '¡·</div>';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '<div align="center" class="STYLE17">';
$jieqiCollect['author']['right'] = '¡¶!¡·</div>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort'] = '';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['left'] = '<meta name="Description" content="';
$jieqiCollect['intro']['right'] = '">';
$jieqiCollect['intro']['middle'] = '~~~~';
$jieqiCollect['articleimage'] = '';
$jieqiCollect['filterimage'] = '';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '';
$jieqiCollect['urlindex'] = '<{articleid}>';
$jieqiCollect['volume'] = '';
$jieqiCollect['chapter']['left'] = '<a class="1" href="~" title="!" target="_blank">';
$jieqiCollect['chapter']['right'] = '</a>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<a class="1" href="';
$jieqiCollect['chapterid']['right'] = '" title="!" target="_blank">!</a>';
$jieqiCollect['chapterid']['middle'] = '~~~~';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '';
$jieqiCollect['urlchapter'] = '<{auto}><{chapterid}>';
$jieqiCollect['content']['left'] = '<span style="font-size:14px;line-height:25px;" zzz="$">';
$jieqiCollect['content']['right'] = '</span>!</div></td>!</tr>!</table></td>!</tr>!</table>';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = '»Ã½£ÊéÃË';
$jieqiCollect['contentreplace'] = 'Êéº£Íø';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect'] = '';

?>