<?php
$jieqiCollect['sitename'] = '风起小说新版';
$jieqiCollect['siteurl'] = 'http://www.fengqiyc.com/';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '0';
$jieqiCollect['autochaptercollect'] = '0';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatarticle'] = '1';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = '';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = 'http://www.fengqiyc.com/index?model=mfront_book&action=bookdetail&bookId=<{articleid}>';
$jieqiCollect['articletitle']['left'] = '<span id="header_bkName">';
$jieqiCollect['articletitle']['right'] = '</span>';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '<span id="header_bkAuthor"><b>作者：</b>';
$jieqiCollect['author']['right'] = '</span>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '<span class="deepRed">类型：</span>';
$jieqiCollect['sort']['right'] = '</div>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword']['left'] = '<span class="deepRed">标签：</span>';
$jieqiCollect['keyword']['right'] = '</div>';
$jieqiCollect['keyword']['middle'] = '!!!!';
$jieqiCollect['intro']['left'] = '<div class="content_child_summary">';
$jieqiCollect['intro']['right'] = '</div>!<div class="webAlert">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<div class="worksCover">!<img src="';
$jieqiCollect['articleimage']['right'] = '" alt="~">!</div>';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = '/fengqi/web/authorCenter/images/bookface.gif';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '<span class="deepRed">状态：</span>巳';
$jieqiCollect['vipstart']['left'] = '<div class="tabContent" style="display:none;">!<div class="chapter_content_text">!<ul>!<li>!<a href="javascript:void(0)" onclick="goRead(\'clickChapter\',$,';
$jieqiCollect['vipstart']['right'] = ',\'/\')"';
$jieqiCollect['vipstart']['middle'] = '$$$$';
$jieqiCollect['sortid']['玄幻修真'] = '1';
$jieqiCollect['sortid']['都市异能'] = '2';
$jieqiCollect['sortid']['惊悚悬疑'] = '3';
$jieqiCollect['sortid']['网游娱乐'] = '4';
$jieqiCollect['sortid']['灵界魔法'] = '5';
$jieqiCollect['sortid']['武侠仙缘'] = '6';
$jieqiCollect['sortid']['官场商战'] = '7';
$jieqiCollect['sortid']['军事历史'] = '8';
$jieqiCollect['sortid']['青春校园'] = '101';
$jieqiCollect['sortid']['婚恋家庭'] = '102';
$jieqiCollect['sortid']['穿越架空'] = '103';
$jieqiCollect['sortid']['职场丽人'] = '104';
$jieqiCollect['sortid']['幻情后宫'] = '105';
$jieqiCollect['sortid']['耽美同人'] = '106';
$jieqiCollect['sortid']['总裁豪门'] = '107';
$jieqiCollect['sortid']['都市高干'] = '108';
$jieqiCollect['sortid']['现代诗'] = '201';
$jieqiCollect['sortid']['古体诗'] = '202';
$jieqiCollect['sortid']['散文诗'] = '203';
$jieqiCollect['sortid']['新歌词'] = '204';
$jieqiCollect['sortid']['散文'] = '205';
$jieqiCollect['sortid']['随笔'] = '206';
$jieqiCollect['sortid']['小说'] = '207';
$jieqiCollect['sortid']['杂文'] = '208';
$jieqiCollect['sortid']['微电影'] = '210';
$jieqiCollect['sortid']['图书库'] = '211';
$jieqiCollect['sortid']['诗歌库'] = '212';
$jieqiCollect['sortid']['default'] = '2';
$jieqiCollect['urlindex'] = 'http://www.fengqiyc.com/index?model=mfront_book&action=readChapterDir&bookId=<{articleid}>';
$jieqiCollect['volume'] = '';
$jieqiCollect['chapter']['left'] = 'onclick="goRead(\'clickChapter\',$,$,\'/\')">!<b class="chapter_title">';
$jieqiCollect['chapter']['right'] = '</b>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = 'onclick="goRead(\'clickChapter\',$,';
$jieqiCollect['chapterid']['right'] = ',\'/\')">!<b class="chapter_title">!</b>';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '';
$jieqiCollect['urlchapter'] = 'http://www.fengqiyc.com/index?model=mfront_book&action=readBook&bookId=<{articleid}>&curChapterNum=<{chapterid}>';
$jieqiCollect['content']['left'] = '<!--chapterContent start-->';
$jieqiCollect['content']['right'] = '<!--chapterContent end-->';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['postdate']['left'] = '<span>更新时间：';
$jieqiCollect['postdate']['right'] = '</span>';
$jieqiCollect['postdate']['middle'] = '!!!!';
$jieqiCollect['contentfilter'] = '<div!>
</div>';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '男生女生最新更新';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://www.fengqiyc.com/index?model=mfront_book&action=bookLibrary&page=<{pageid}>';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<span class="collectBook" onclick="collectBook(';
$jieqiCollect['listcollect']['0']['articleid']['right'] = ')">收藏本书</span>';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '1';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '1000';

?>