<?php
$jieqiCollect['sitename'] = '努努书坊';
$jieqiCollect['siteurl'] = 'http://www.kanunu8.com/';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '1';
$jieqiCollect['referer'] = '1';
$jieqiCollect['autochaptercollect'] = '1';
$jieqiCollect['chapteridorder'] = '0';
$jieqiCollect['cleantargetsiterepeatchapter'] = '0';
$jieqiCollect['cleansiterepeatchapter'] = '0';
$jieqiCollect['wget'] = '0';
$jieqiCollect['makeset'] = 'makehtml';
$jieqiCollect['pagecharset'] = 'gbk';
$jieqiCollect['firstflag'] = '0';
$jieqiCollect['urlarticle'] = '<{articleid}>';
$jieqiCollect['articletitle']['0']['left'] = '<h$><!><font color="#dc143c">';
$jieqiCollect['articletitle']['0']['right'] = '</font></!></h$></td>';
$jieqiCollect['articletitle']['0']['middle'] = '!!!!';
$jieqiCollect['articletitle']['1']['left'] = '<h$><!>';
$jieqiCollect['articletitle']['1']['right'] = '</!></h$></td>';
$jieqiCollect['articletitle']['1']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '作者：';
$jieqiCollect['author']['right'] = ' 发布时间';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '<a href=\'http://www.kanunu8.com/\'>首页</a>><a href=\'~\'>';
$jieqiCollect['sort']['right'] = '</a>>文章内容</FONT>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['type'] = '';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['0']['left'] = '<strong>内容简介：</strong><br />';
$jieqiCollect['intro']['0']['right'] = '<br />';
$jieqiCollect['intro']['0']['middle'] = '!!!!';
$jieqiCollect['intro']['1']['left'] = '<td class="p10-$">';
$jieqiCollect['intro']['1']['right'] = '<br />';
$jieqiCollect['intro']['1']['middle'] = '!!!!';
$jieqiCollect['intro']['2']['left'] = '<strong>内容简介：</strong><br />';
$jieqiCollect['intro']['2']['right'] = '</td>';
$jieqiCollect['intro']['2']['middle'] = '!!!!';
$jieqiCollect['articleimage']['left'] = '<img height="$" alt="~" width="$" border="1" src="';
$jieqiCollect['articleimage']['right'] = '" />';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = '';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '';
$jieqiCollect['sortid']['外国文学'] = '204';
$jieqiCollect['sortid']['default'] = '204';
$jieqiCollect['urlindex'] = '<{articleid}>';
$jieqiCollect['volume']['0']['left'] = '<td colspan="4" align="center"><strong>';
$jieqiCollect['volume']['0']['right'] = '</strong></td>';
$jieqiCollect['volume']['0']['middle'] = '!!!!';
$jieqiCollect['volume']['1']['left'] = '<td colspan="3">';
$jieqiCollect['volume']['1']['right'] = '</td>';
$jieqiCollect['volume']['1']['middle'] = '!!!!';
$jieqiCollect['volume']['2']['left'] = '<td align="center" colspan="4"><strong>';
$jieqiCollect['volume']['2']['right'] = '</strong></td>';
$jieqiCollect['volume']['2']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = '><a !href="~">';
$jieqiCollect['chapter']['right'] = '</a>!</td>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '><a !href="';
$jieqiCollect['chapterid']['right'] = '">!</a>!</td>';
$jieqiCollect['chapterid']['middle'] = '~~~~';
$jieqiCollect['chapterfilter'] = '';
$jieqiCollect['chapterreplace'] = '';
$jieqiCollect['cleanchapter'] = '';
$jieqiCollect['urlchapter'] = '<{auto}><{chapterid}>';
$jieqiCollect['content']['0']['left'] = '<div id=\'content\' class="connie">';
$jieqiCollect['content']['0']['right'] = '</div>!</td>!</tr>!</table>!<hr>';
$jieqiCollect['content']['0']['middle'] = '****';
$jieqiCollect['content']['1']['left'] = '<td width="820" align="left" bgcolor="#FFFFFF">';
$jieqiCollect['content']['1']['right'] = '</td>!<td width="30" align="center" bgcolor="#FFFFFF"></td>';
$jieqiCollect['content']['1']['middle'] = '****';
$jieqiCollect['content']['2']['left'] = '<div id="content"!>';
$jieqiCollect['content']['2']['right'] = '</div>!<hr>!<table width="780" border="0" align="center" cellpadding="0" cellspacing="0">';
$jieqiCollect['content']['2']['middle'] = '****';
$jieqiCollect['contentfilter'] = '';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '外国文学';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://book.kanunu.org/files/world/8-<{pageid}>.html';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<td width=\'60%\'>!<a href=\'/book4/';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '/index.html\' title=\'!\'>!</a></td>!<td width=\'2%\'></td>';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '';
$jieqiCollect['listcollect']['1']['title'] = '世界文学';
$jieqiCollect['listcollect']['1']['urlpage'] = 'http://www.kanunu8.com/files/world/8-<{pageid}>.html';
$jieqiCollect['listcollect']['1']['articleid']['left'] = '<td width=\'98%\'> <a href=\'';
$jieqiCollect['listcollect']['1']['articleid']['right'] = '\' target=\'_blank\'';
$jieqiCollect['listcollect']['1']['articleid']['middle'] = '!!!!';
$jieqiCollect['listcollect']['1']['startpageid'] = '1';
$jieqiCollect['listcollect']['1']['nextpageid'] = '';
$jieqiCollect['listcollect']['1']['maxpagenum'] = '12';

?>